CREATE SCHEMA IF NOT EXISTS public;

-- Таблица users
CREATE TABLE IF NOT EXISTS public.users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

-- Таблица items
CREATE TABLE IF NOT EXISTS public.items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(512)                            NOT NULL,
    owner_id    BIGINT                                  NOT NULL,
    available   BOOLEAN                                 NOT NULL,
    request_id  BIGINT,
    CONSTRAINT pk_item PRIMARY KEY (id),
    CONSTRAINT fk_item_owner FOREIGN KEY (owner_id) REFERENCES public.users (id)
);

-- Таблица bookings
CREATE TABLE IF NOT EXISTS public.bookings
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    booking_start TIMESTAMP(0),
    booking_end   TIMESTAMP(0),
    item_id       BIGINT                                  NOT NULL,
    booker_id     BIGINT                                  NOT NULL,
    status        VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_bookings PRIMARY KEY (id),
    CONSTRAINT fk_booking_item FOREIGN KEY (item_id) REFERENCES public.items (id),
    CONSTRAINT fk_booking_booker FOREIGN KEY (booker_id) REFERENCES public.users (id),
    CONSTRAINT chk_booking_status CHECK (
        status IN ('WAITING', 'APPROVED', 'REJECTED', 'CANCELED')
        )
);

-- Таблица comments
CREATE TABLE IF NOT EXISTS public.comments
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT                                  NOT NULL,
    item_id BIGINT                                  NOT NULL,
    comment VARCHAR(1000)                           NOT NULL,
    created TIMESTAMP(0)                            NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id),
    CONSTRAINT fk_comment_user FOREIGN KEY (user_id) REFERENCES public.users (id),
    CONSTRAINT fk_comment_item FOREIGN KEY (item_id) REFERENCES public.items (id)
);
